### ISSUE TITLE
Weird behaviour of the Show More / Show Less buttons

### ISSUE THREAD

**Issue by sarkadiadam** [shellpea/advanced-elasticsuite-catalog#10]
After you check a filter, the filter content box automatically gets expanded and the "Show more" button is still showing up at the end of the list.

![Screenshot 2023-06-28 at 17 02 47](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/49277901/b15fe5a0-a782-4d97-a74e-91614bec525c)

And after you interact with the Show more / less buttons, the previously selected filter gets un-checked (only visually because the product list still shows the correct products)

![Screenshot 2023-06-28 at 17 05 45](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/49277901/ebcae499-1adf-4cce-9bfe-3ee010e492bc)

**Comment by AlexDroomer** [comment]
@sarkadiadam Thanks for the feedback, I'll try to fix these bugs in the near future 🙌

**Comment by AlexDroomer** [comment]
@sarkadiadam Hi, please check new module version 1.2.2
