### ISSUE TITLE
Ajax Layered Navigation Filter Randomly error in Hyva theme

### ISSUE THREAD

**Issue by rahul-navigate** [shellpea/advanced-elasticsuite-catalog#11]
I have installed the module using composer with below command

`composer require "shellpea/magento-advanced-elasticsuite-catalog":"^1.2.1"`

It seems all good while i am doing test on product listing page with shop by filters i see following errors on random result.

Even i did checked the inspect element the component is there.

Reference error is attached.

![attribute](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/131374454/37819b18-a09e-40ae-9c49-61ed2d582cf5)

**Comment by AlexDroomer** [comment]
@rahul-navigate Hi, please check new version 1.2.2

**Comment by rahul-navigate** [comment]
Hi @AlexDroomer 

Thanks for sharing update.

As suggested, I did tried to upgrade version using composer to 1.2.2

`composer require "shellpea/magento-advanced-elasticsuite-catalog":"^1.2.2"`

But it seems 1.2.2 version is not available in composer

Problem 1
    - Root composer.json requires shellpea/magento-advanced-elasticsuite-catalog ^1.2.2, found shellpea/magento-advanced-elasticsuite-catalog[1.2.x-dev] but it does not match your minimum-stability.
  Problem 2
    - Root composer.json requires hyva-themes/magento2-shellpea-advanced-elasticsuite-catalog dev-main -> satisfiable by hyva-themes/magento2-shellpea-advanced-elasticsuite-catalog[dev-main].
    - hyva-themes/magento2-shellpea-advanced-elasticsuite-catalog dev-main requires shellpea/magento-advanced-elasticsuite-catalog * -> found shellpea/magento-advanced-elasticsuite-catalog[v1.0.0, v1.2.0, v1.2.1] but it conflicts with your root composer.json require (^1.2.2).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Ref : https://prnt.sc/FwN2JthcPp_q

so do i need to test with dev-main branch ?

**Comment by AlexDroomer** [comment]
@rahul-navigate I'm sorry, due to my typo in semver the module was not updated on packagist, it's already fix, try it out 🙏

**Comment by rahul-navigate** [comment]
HI @AlexDroomer , Thanks for quick update and yes now version is available on composer.

Thanks Again :)
