### ISSUE TITLE
Issue with Varnish cache

### ISSUE THREAD

**Issue by xcom-magento** [shellpea/advanced-elasticsuite-catalog#15]
Hi, we have an issue with this module in combination with Varnish FPC.

**Steps to reproduce:**

- Open category page and apply a filter (for example the price filter), this works correctly (when the url is not cached before).
- Remove the active filter individually or by the 'Clear all' button

**Expected result**

- The filtered collection is restored and all products from that category are shown.

**Actual result**

- There is an error throwned -> _"SyntaxError: Unexpected token '<', " <!doctype "... is not valid JSON"_

This is because the fetch gets the full html response from the Varnish cache instead of the JSON. Also when you refresh a page when filtered (for example _?price=17-56_ is in the url), you will see a json output instead of the page.

![image](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/50484971/1a4ac31e-b47d-4700-aad4-569bb30bdba3)

Magento version: 2.4.4-p2
PHP version: 7.4
Module version: 1.2.3
Varnish 6

**Comment by ldrooij** [comment]
We solved it for now by updating sub vcl_hash in our varnish VCL adding

```
    # To make sure XMLHttp calls have their own cache
    if (req.http.X-Requested-With) {
        hash_data(req.http.X-Requested-With);
    }
```

It seems this can only be ommitted by making sure the url is unique since the X-Magento-Vary cookie cannot be updated between making the ajax call and refreshing the page.
