### ISSUE TITLE
Module not working yet on Hyva 1.3.x ?

### ISSUE THREAD

**Issue by ekomurz** [shellpea/advanced-elasticsuite-catalog#18]
We're installing/testing this module, but it seems to break a number of things on the category page.
Any idea how we can get this working on 1.3.x ?

**Comment by AlexDroomer** [comment]
@ekomurz Hello, I haven’t tested it on this version yet, now I’ll try to install it and see what the problem is, thanks for the issue

**Comment by AlexDroomer** [comment]
@ekomurz let's try install last version 
```
composer require "shellpea/magento-advanced-elasticsuite-catalog":"^1.2.4"
```

**Comment by ekomurz** [comment]
We did some testing, and results (number of products shown) does not seem to go correct in all cases ?
We'll investigate this further, trying to find the cause - will update you later this week.

**Comment by AlexDroomer** [comment]
Hi @ekomurz! Is this issue still relevant or can I close this issue?

**Comment by ekomurz** [comment]
Hi @AlexDroomer - let me test your newest version the coming days. I'll give you feedback somewher tuesday/wednesday.
