### ISSUE TITLE
Errors after clear all active filters

### ISSUE THREAD

**Issue by mikesteeghs** [shellpea/advanced-elasticsuite-catalog#21]
When you visit a URL directly with one or more filters active and clear those filters, the console will be full of errors (see screenshot below).

**Steps to reproduce**

1. Visit the product overview page
2. Select an attribute filter
3. Reload the page, or re-enter the current URL. So you're now visiting a URL with a filter active directly
4. Click the 'Clear all' button to remove all active filters

**What is expected to happen**

The active filters will be cleared and the product list is updated.

**What actually happens**

The active filters are cleared, the product list is updated, but also the console is full of errors.
Also, all the filters are expanded with a 'Show more' button.

![image](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/7780853/6f0e6fe0-ca26-4096-9c72-7362c0904f2a)

**Comment by mikesteeghs** [comment]
I just found out this only happens in the following situation:

- For example, on the category page you have the filters color and material
- You select a filter from the materials
- The products that are now visible (the filtered products) shouldn't have a color set, so the color filter will disappear
- In this case, if the URL with 1 param doesn't have the color filter, but the category page has the color filter, you should visit the URL with the selected material directly
- At this point, when you click 'Clear all' or deselect the active filter, the errors will occur.

**Comment by AlexDroomer** [comment]
Hi, @mikesteeghs, these errors are related to the problem of x-data reinitialization on the fly in Alpine.js and I'm still in the process of finding a solution to this problem

**Comment by AlexDroomer** [comment]
@mikesteeghs I solve this issue, check last version
