### ISSUE TITLE
Ajax Layered Navigation Price slider not updating on other product attribute filter apply

### ISSUE THREAD

**Issue by rahul-navigate** [shellpea/advanced-elasticsuite-catalog#22]
I am having shellpea/magento-advanced-elasticsuite-catalog:1.2.6 installed along with hyva theme 1.3.7

Steps to reproduce:

Open category page with price filter (as as slider) active
Click on product attribute filter like brand, color, etc. -> Apply filter

Expected result
The price slider should also update  as range of product collection and product count should also applied (like other product attribute)

Actual result
The price slider is not update on ajax request / It update when we do page refresh manually.

Magento version: 2.4.6-p1
PHP version: 8.1
Module version: 1.2.6

**Comment by AlexDroomer** [comment]
Hi @rahul-navigate, the functionality you described was still in the process of implementation, at the moment I cannot offer a quick solution, since this requires state synchronization with Alpine.store, I will mention this issue as soon as the solution is ready, thanks for the feedback

**Comment by rahul-navigate** [comment]
> Hi @rahul-navigate, the functionality you described was still in the process of implementation, at the moment I cannot offer a quick solution, since this requires state synchronization with Alpine.store, I will mention this issue as soon as the solution is ready, thanks for the feedback

@AlexDroomer thanks for sharing an update. we will looking forward to it. Thanks !

**Comment by pknap** [comment]
Hey @AlexDroomer, will the fix mentioned in your previous comment be part of next release? If it is not yet in the process of development could you shed a bit more light on how can this be fixed using Alpine.store?

I can see that currently `category` object is stored in Alpine.store, so is the idea to have priceSlider property stored within category object and then reinit this with new min/max price and product count on `loadActualFilters`?
