### ISSUE TITLE
Slider attribute is adding filter value twice to url

### ISSUE THREAD

**Issue by koenner01** [shellpea/advanced-elasticsuite-catalog#23]
We have an attribute set to be displayed as a slider which continuously adds the value you select to the url (even though there is already a value present);

Example 
`https://some-url/products?slider=1-2`
If you would then select a new value for the "slider" attribute you would get
`https://some-url/products?slider=1-2&slider=1-3`

This keeps repeating everytime you select a value.

I traced the code back to /view/frontend/templates/catalog/layer/filter/js/slider-filter-js.phtml in this section
```
_applyRange: function () {
    var range = {
        from: this._getOriginalValue(this.minprice) * (1 / this.rate),
        to: this._getOriginalValue(this.maxprice) * (1 / this.rate),
    };
    const searchParams = () => {
        let searchParams = new URL(window.location).searchParams
        searchParams.delete('price')
        searchParams.delete('q')

        return searchParams.size !== 0 ? '&' + searchParams.toString() : ''
    }
    this.url = this._unescape(this.options.urlTemplate.replace('<%- from %>', range.from).replace('<%- to %>', range.to) + searchParams());
},
```

Also unsure why the "price" and "q" are already being removed;
It could seem logical for price because this bug would also apply for that attribute if it's displayed as a slider, but "q" I have no idea. 

Using
```
smile/elasticsuite: 2.11.6.1
hyva-themes/magento2-smile-elasticsuite: 1.2.3
shellpea/magento-advanced-elasticsuite-catalog: v1.2.6
```

**Comment by AlexDroomer** [comment]
@koenner01 Hi, thank you for your feedback, indeed, the word “price” is incorrect to use. For a quick fix you can override the specified file and replace the price with this code 
```js
searchParams.delete(this.options.requestVar)
```
and it will work for every type of slider you use 🙏
p.s. I can’t remember why I need to remove 'q', but there was some case in which it caused an error, if this causes unexpected behavior, you can remove this line, I will try to check if this causes an error in the default hyva theme and the next release is 1.2.7 will be released with these changes
