### ISSUE TITLE
Module breaks the search results page

### ISSUE THREAD

**Issue by sarkadiadam** [shellpea/advanced-elasticsuite-catalog#5]
Hello!

Using this module on a Hyva project (Default un-modified Hyva theme):

smile/elasticsuite: 2.11.1.1
hyva-themes/magento2-smile-elasticsuite: 1.2.0
hyva-themes/magento2-default-theme: 1.2.3

But the **search results** page breaks with the following error:

Error: Call to a member function setUniqueId() on bool in /vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/templates/catalog/layer/filter/attribute.phtml:16

This seems to be happening because in:
- In vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/layout/hyva_catalogsearch_result_index.xml the "attribute-filter-js" block is removed

![Screenshot 2023-05-25 at 11 34 58](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/49277901/7e6dc499-bcc7-4bfe-ba54-d93c16706d37)

- In vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/templates/catalog/layer/filter/attribute.phtml the "attribute-filter-js" block is being loaded.

![Screenshot 2023-05-25 at 11 35 09](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/49277901/f88ea910-effb-4210-9743-f4776f8b582a)

Is this intended or am I missing something?

Thank you!

**Comment by AlexDroomer** [comment]
@sarkadiadam Hello, thanks for the detailed description. No such behavior was intended. When switching to alpine v3, the search page was not tested in the new version of the module 1.2.x
