### ISSUE TITLE
Javascript breaks when HTML minify is enabled.

### ISSUE THREAD

**Issue by sarkadiadam** [shellpea/advanced-elasticsuite-catalog#7]
In `vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/templates/configuration.phtml` Line 17 there is a return statement that uses JS template literals:

```
get clearUrl() {
    const { protocol, host, pathname, searchParams } = new URL(window.location)

    return `${protocol}//${host}${pathname}${searchParams.has('q') ? '?q=' + searchParams.get('q').toString() : ''}`;
},
```

![Screenshot 2023-06-28 at 16 02 48](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/49277901/98655f0f-aa2f-4e7b-a9db-c22e5b50e29d)

The problem is that there is a double back-slash string inside that template literal and the HTML minifier cannot interpret that properly in .phtml files in this context. My guess is that it turns everything after "//" into a comment.

I suggest replacing the clearUrl() method with something like:

```
get clearUrl() {
    const { protocol, host, pathname, searchParams } = new URL(window.location),
    qParam = searchParams.has('q') ? '?q=' + searchParams.get('q').toString() : '',
    endParam = protocol + '//' + host + pathname + qParam;

    return endParam;
},

```

**Comment by AlexDroomer** [comment]
I have added changes to fix this issue 🙂
```javascript
get clearUrl() {
    const { protocol, host, pathname, searchParams } = new URL(window.location.href);
    const queryParam = searchParams.has('q') ? '?q=' + searchParams.get('q').toString() : '';
    return protocol + '//' + host + pathname + queryParam;
},
```
